import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { compareParts } from './comparison';
import { parseDocument } from './parser';
import type { Comparison, SourceKind, Upload } from './types';
import './styles.css';
import './export.css';
import './overrides.css';

const ACCEPT = '.xlsx,.xls,.csv,.doc,.docx';
const labels: Record<SourceKind, string> = { bom: 'Drop BOM / Cutting List here', jobcard: 'Drop Nesting Job Card here' };
function Uploader({ kind, upload, onFile, countLabel }: { kind: SourceKind; upload?: Upload; onFile: (file: File) => void; countLabel?: string }) {
  const [drag, setDrag] = useState(false);
  return <div className={`dropzone ${drag ? 'drag' : ''} ${upload?.status || ''}`} onDragOver={e => { e.preventDefault(); setDrag(true); }} onDragLeave={() => setDrag(false)} onDrop={e => { e.preventDefault(); setDrag(false); const file = e.dataTransfer.files[0]; if (file) onFile(file); }} onClick={() => document.getElementById(`${kind}-file`)?.click()}>
    <input id={`${kind}-file`} type="file" accept={ACCEPT} hidden onChange={e => e.target.files?.[0] && onFile(e.target.files[0])} />
    <div className="drop-icon">⇧</div><div className="drop-title">{labels[kind]}</div><div className="drop-sub">Drag and drop or <span>browse files</span></div>
    {upload && <div className="file-state"><strong>{upload.file.name}</strong><small>{upload.status === 'reading' ? 'Reading locally…' : upload.status === 'valid' ? `${countLabel || `${upload.parts?.length || 0} parts read`} · ${upload.file.type || kind.toUpperCase()}` : upload.message}</small>{upload.status === 'valid' && <i>✓</i>}</div>}
  </div>;
}
function Stat({ label, value, tone }: { label: string; value: number; tone?: string }) { return <div className={`stat ${tone || ''}`}><span>{label}</span><strong>{value}</strong></div>; }
function App() {
  const [files, setFiles] = useState<Partial<Record<SourceKind, Upload>>>({}); const [results, setResults] = useState<Comparison[]>([]); const [filter, setFilter] = useState('all'); const [running, setRunning] = useState(false); const [exportOpen, setExportOpen] = useState(false); const [exportSelection, setExportSelection] = useState({ all: true, critical: true, warning: true, revision: true });
  const setFile = async (kind: SourceKind, file: File) => { const allowed = ['xlsx', 'xls', 'csv', 'doc', 'docx']; if (!allowed.includes(file.name.split('.').pop()?.toLowerCase() || '')) { setFiles(f => ({ ...f, [kind]: { file, status: 'error', message: 'Unsupported file type.' } })); return; } setFiles(f => ({ ...f, [kind]: { file, status: 'reading' } })); try { const parts = await parseDocument(file, kind); if (!parts.length) throw new Error('No recognizable part rows were found in this file.'); setFiles(f => ({ ...f, [kind]: { file, status: 'valid', parts } })); } catch (error) { setFiles(f => ({ ...f, [kind]: { file, status: 'error', message: error instanceof Error ? error.message : 'Could not read this file.' } })); } };
  const run = () => { if (files.bom?.parts && files.jobcard?.parts) { setRunning(true); setTimeout(() => { setResults(compareParts(files.bom!.parts!, files.jobcard!.parts!)); setRunning(false); }, 180); } };
  const sortedResults = useMemo(() => [...results].sort((a, b) => ({ critical: 0, warning: 1, revision: 1, match: 2 }[a.severity] - { critical: 0, warning: 1, revision: 1, match: 2 }[b.severity])), [results]); const filtered = filter === 'all' ? sortedResults : sortedResults.filter(r => r.severity === filter); const counts = { matches: results.filter(r => r.severity === 'match').length, warnings: results.filter(r => r.severity === 'warning' || r.severity === 'revision').length, critical: results.filter(r => r.severity === 'critical').length }; const jobCardTotal = files.jobcard?.parts?.reduce((total, part) => total + (part.quantity ?? 1), 0) || 0;
  const downloadCsv = (rows: Comparison[]) => { const head = ['Status', 'BOM part', 'Job-card part', 'BOM quantity', 'Job-card quantity', 'BOM thickness', 'Job-card thickness', 'Explanation']; const lines = [head, ...rows.map(r => [r.severity, r.bomPart, r.jobPart, r.bomQty, r.jobQty, r.bomThickness, r.jobThickness, r.explanation])].map(row => row.map(v => `"${String(v).replaceAll('"', '""')}"`).join(',')); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([lines.join('\n')], { type: 'text/csv' })); link.download = 'ims-sheet-metal-audit.csv'; link.click(); setExportOpen(false); };
  const reset = () => { setFiles({}); setResults([]); setFilter('all'); setExportOpen(false); }; const exportRows = exportSelection.all ? sortedResults : sortedResults.filter(r => (exportSelection.critical && r.severity === 'critical') || (exportSelection.warning && r.severity === 'warning') || (exportSelection.revision && r.severity === 'revision')); const toggleExport = (key: keyof typeof exportSelection) => setExportSelection(s => key === 'all' ? { all: !s.all, critical: !s.all, warning: !s.all, revision: !s.all } : { ...s, all: false, [key]: !s[key] }); const tabs = [['all', 'All'], ['critical', 'Critical'], ['warning', 'Warnings'], ['revision', 'Revision differences'], ['match', 'Matches']];
  const report = results.length > 0 && <section className="results report-screen"><div className="report-topbar"><strong>IMS SHEET METAL AUDITOR</strong><span>COMPARISON REPORT</span><button onClick={reset}>← Back to uploads</button></div><div className="result-head"><div><label>AUDIT OUTPUT</label><h2>Comparison results</h2></div><div className="result-actions"><button onClick={() => setExportOpen(true)}>Export CSV ↓</button><button onClick={reset}>Start new comparison</button></div></div><div className="stats"><Stat label="Total BOM parts" value={files.bom?.parts?.length || 0} /><Stat label="Total job-card parts" value={jobCardTotal} /><Stat label="Exact matches" value={counts.matches} tone="match" /><Stat label="Warnings" value={counts.warnings} tone="warning" /><Stat label="Critical issues" value={counts.critical} tone="critical" /></div><div className="filterbar">{tabs.map(([value, label]) => <button className={filter === value ? 'selected' : ''} onClick={() => setFilter(value)} key={value}>{label} <em>{value === 'all' ? results.length : results.filter(r => r.severity === value).length}</em></button>)}</div><div className="table-wrap"><table><thead><tr><th>Status</th><th>BOM part</th><th>Job-card part</th><th>Qty</th><th>Thickness</th><th>Explanation</th></tr></thead><tbody>{filtered.map(r => <tr key={r.id}><td><span className={`status ${r.severity}`}>{r.severity === 'match' ? 'EXACT MATCH' : r.severity === 'revision' ? 'REVISION' : r.severity.toUpperCase()}</span></td><td>{r.bomPart}</td><td>{r.jobPart}</td><td>{r.bomQty} <small>/ {r.jobQty}</small></td><td>{r.bomThickness} <small>/ {r.jobThickness}</small></td><td>{r.explanation}</td></tr>)}</tbody></table></div></section>;
  return <><header><img src="/ims-logo-primary.png" /><div className="header-title">IMS SHEET METAL AUDITOR<span>PRE-PRODUCTION CONTROL</span></div><div className="workspace-pill">◉ &nbsp; Local workspace</div><button className="hub disabled" disabled>Back to Operations Hub <b>→</b></button></header><main>{report || <><section className="intro"><div><label>QUALITY CONTROL / PRODUCTION READINESS</label><h1>Audit your sheet-metal job<br />before it reaches the floor.</h1><p>Compare the released BOM against the nesting job card locally, catch dangerous part changes, and give production a clear decision.</p></div></section><section className="upload-grid"><Uploader kind="bom" upload={files.bom} onFile={file => setFile('bom', file)} /><Uploader kind="jobcard" upload={files.jobcard} countLabel={jobCardTotal ? `${jobCardTotal} placed parts · ${files.jobcard?.parts?.length || 0} unique rows` : undefined} onFile={file => setFile('jobcard', file)} /></section><div className="action-row"><span>{files.bom?.status === 'valid' && files.jobcard?.status === 'valid' ? 'Both documents ready for comparison.' : 'Add two valid documents to begin.'}</span><button className="primary" disabled={files.bom?.status !== 'valid' || files.jobcard?.status !== 'valid' || running} onClick={run}>{running ? 'Comparing…' : 'Run comparison'} <b>→</b></button></div></>}</main><footer><span>IMS South Africa Management System</span><span>Workspace data is saved securely on this device</span></footer>{exportOpen && <div className="export-screen"><div className="export-card"><div className="export-head"><div><label>REPORT EXPORT</label><h2>Export CSV</h2><p>Select the audit categories to include in your download.</p></div><button className="close-export" onClick={() => setExportOpen(false)}>×</button></div><div className="export-options">{([['all', 'All', 'Include the complete comparison report'], ['critical', 'Critical', 'Missing parts, quantity/thickness mismatches and suspected wrong parts'], ['warning', 'Warnings', 'Name mismatches and extra job-card parts'], ['revision', 'Revision Differences', 'Revision-only name changes requiring confirmation']] as const).map(([key, label, description]) => <label className={`export-option ${exportSelection[key] ? 'checked' : ''}`} key={key}><input type="checkbox" checked={exportSelection[key]} onChange={() => toggleExport(key)} /><span><strong>{label}</strong><small>{description}</small></span></label>)}</div><div className="export-footer"><span>{exportRows.length} rows selected</span><button className="primary" disabled={!exportRows.length} onClick={() => downloadCsv(exportRows)}>Download selected CSV ↓</button></div></div></div>}</>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
